CREATE SEQUENCE GEN_PRODUTO_ID START WITH 0 INCREMENT BY 1;
ALTER SEQUENCE GEN_PRODUTO_ID RESTART WITH 34;

/* Old syntax is:
CREATE GENERATOR GEN_PRODUTO_ID;
SET GENERATOR GEN_PRODUTO_ID TO 34;
*/

/* Existing privileges on this sequence */

GRANT USAGE ON SEQUENCE GEN_PRODUTO_ID TO SYSDBA WITH GRANT OPTION;
