/******************************************************************************/
/*                 Generated by IBExpert 22/01/2018 09:50:33                  */
/******************************************************************************/

/******************************************************************************/
/*        Following SET SQL DIALECT is just for the Database Comparer         */
/******************************************************************************/
SET SQL DIALECT 3;



/******************************************************************************/
/*                                   Tables                                   */
/******************************************************************************/


CREATE GENERATOR GEN_PRODUTO_ID;

CREATE TABLE PRODUTO (
    ID             INTEGER NOT NULL,
    CODIGOBARRA    VARCHAR(30),
    UNIDADE        CHAR(2),
    PESO           NUMERIC(12,3),
    DESCRICAO      VARCHAR(300),
    ESTOQUEMINIMO  NUMERIC(12,3),
    ESTOQUEMAXIMO  NUMERIC(12,3),
    ESTOQUEATUAL   NUMERIC(12,3),
    DTUPDATE       TIMESTAMP,
    DTDELETE       TIMESTAMP,
    ISDELETE       BOOLEAN,
    DTINSERT       TIMESTAMP
);




/******************************************************************************/
/*                                Primary keys                                */
/******************************************************************************/

ALTER TABLE PRODUTO ADD CONSTRAINT PRODUTO_ID_PKEY PRIMARY KEY (ID);


/******************************************************************************/
/*                                  Triggers                                  */
/******************************************************************************/



SET TERM ^ ;



/******************************************************************************/
/*                            Triggers for tables                             */
/******************************************************************************/



/* Trigger: PRODUTO_BI */
CREATE OR ALTER TRIGGER PRODUTO_BI FOR PRODUTO
ACTIVE BEFORE INSERT POSITION 0
as
begin
  if (new.id is null) then
    new.id = gen_id(gen_produto_id,1);
end
^

SET TERM ; ^



/******************************************************************************/
/*                                 Privileges                                 */
/******************************************************************************/
